### ISSUE TITLE
Why layerscale isn't used in the work?

### ISSUE THREAD

**Issue by Ga-Lee** [ziyuwwang/DynaMixer#1]
Hello! Thank you  for your wonderful job!
I notice that it seems that layerscale is not used in the work, and I wonder what is the reason.
Have you tried layerscale when doing experiment, does it help nothing? 
And another question is that what is  '**skip_lam**' used for in  vision_model.py ?
Appreciate for your reply! : )

**Comment by ziyuwwang** [comment]
Hi! Thank you for your attention.
For a fair comparison, we basically adopt the experimental setting of ViP, in which layerscale is not used. Actually, we don't think layerscale is the focus of our research. We haven't tried layerscale in our experiment, but I think it may help to boost the performance. 
As for 'skip_lam', it's just a hyperparameter for residual structure, which is used to avoid the residual being too large or too small. Generally, it can be set to 1 in experiments.
Hope this answer can be helpful to you.

**Comment by Ga-Lee** [comment]
> Hi! Thank you for your attention. For a fair comparison, we basically adopt the experimental setting of ViP, in which layerscale is not used. Actually, we don't think layerscale is the focus of our research. We haven't tried layerscale in our experiment, but I think it may help to boost the performance. As for 'skip_lam', it's just a hyperparameter for residual structure, which is used to avoid the residual being too large or too small. Generally, it can be set to 1 in experiments. Hope this answer can be helpful to you.

Thank you for your reply!
